version: '3.4'
services:
  api:
    build: .
    depends_on:
      - database
    networks:
      - default
    ports:
      - 5000:5000
    restart: always
  database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  database-data: