version: '3.4'
services:
  alarm-api:
    build: .
    depends_on:
      - alarm-db
    networks:
      - default
    ports:
      - 5000:5000
    restart: unless-stopped
  alarm-db:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  database-data: